### ISSUE TITLE
FileNotFound Error even the folder has been created

### ISSUE THREAD

**Issue by zhwj888** [allanj/pytorch_neural_crf#1]
Hi
I have created the model_files and results folders as the instruction required.
But I still get this error:

FileNotFoundError: [Errno 2] No such file or directory: 'model_files/lstm_200_crf_conll2003_-1_dep_none_elmo_sgd_lr_0.01.m'

Could you please help me with that? Thanks

My working enviroment:
Anaconda, pytorch 1.1.0

**Comment by allanj** [comment]
Sorry about this error. I think it is caused by the default `mode` is `"test"`. I have changed the default value to `train`. You can simply `git pull` or change this line as well.

```python
parser.add_argument('--mode', type=str, default='train', choices=["train","test"], help="training mode or testing mode")
```

FYI, in this version, you also don't need to make sure the model_files and results folders exists as I made checking before running the model.
